# Generated by Django 4.2.3 on 2023-07-28 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_detail',
            name='No_of_Reviews',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course_detail',
            name='No_of_Subscribers',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cource_category',
            name='Image',
            field=models.ImageField(blank=True, upload_to='Cource_Category'),
        ),
        migrations.AlterField(
            model_name='course_detail',
            name='Image',
            field=models.ImageField(blank=True, upload_to='Cource'),
        ),
        migrations.CreateModel(
            name='Subsribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.course_detail')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.student')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now=True)),
                ('Comments', models.CharField(max_length=100)),
                ('Rating', models.IntegerField()),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.course_detail')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.student')),
            ],
        ),
    ]
