# Generated by Django 4.2.3 on 2023-07-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_course_detail_no_of_reviews_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_detail',
            name='Date',
            field=models.DateField(default='2023-7-28'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course_detail',
            name='Published',
            field=models.CharField(max_length=20),
        ),
    ]
